### ISSUE TITLE
Issues with manipulation target pose

### ISSUE THREAD

**Issue by FabianEP11** [temoto-telerobotics/temoto_robot_manager#5]
From the robot_manager_interface we are passing a PoseStamped, but when it reaches the robot.cpp, in the moveit function it is using just the Pose.
https://github.com/temoto-framework/temoto_robot_manager/blob/rr-devel/src/robot.cpp#L558
`group_it->second->setPoseTarget(target_pose.pose);`
It should be
`group_it->second->setPoseTarget(target_pose);`

Additionally, sometimes the robot manager cannot set the right goal for the end effector (in setPoseTarget or setNamedTarget), but it still generates an empty plan making the manipulator move to its zero state, which is an undesirable behavior. 

Suggested solution: 
Validate the target pose using the boolean from the setPoseTarget and setNamedTarget 
```
if (!group_it->second->setNamedTarget(named_target))
  {
    is_plan_valid_ = false;
    throw CREATE_ERROR(temoto_core::error::Code::ROBOT_PLAN_FAIL,"Planning to named target pose '%s' failed.", named_target);
  }
```

**Comment by RValner** [comment]
Yeah, the suggestion makes sense.
